utf8 encode stderr
Without this stderr can't be parsed and produces an error like:

```
error = options.name + ' nvm failed with: ' + data.replace('\n', '') + ', use -i option to install missing node versions!';
                                                             ^

TypeError: data.replace is not a function
```